Controllers films users
Anthony-Elvek/java-filmorate pull request #2
Opened 2022-12-07 18:18 UTC by Anthony-Elvek

2022-12-08 14:04 UTC, NikolaiDem requested changes

2022-12-08 14:04 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/validator/FilmValidatorTest.java
> +public class FilmValidatorTest {
Починить тесты

2022-12-08 14:04 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/validator/UserValidatorTest.java
> +public class UserValidatorTest {
Починить тесты

2022-12-08 22:16 UTC, Anthony-Elvek commented on src/main/java/ru/yandex/practicum/controller/FilmController.java
> +@JsonAutoDetect(getterVisibility = JsonAutoDetect.Visibility.NONE)
забыл убрать

2022-12-08 22:18 UTC, Anthony-Elvek commented on src/main/java/ru/yandex/practicum/validator/UserNameValidator.java
> +            user.setName(user.getLogin());
Я так и не понял как работать с сервисами, сделал проверку в контроллере, понимаю что не правильно но если у вас есть хороший источник как с ними работать, постараюсь сразу переделать

2022-12-08 22:19 UTC, Anthony-Elvek commented on src/test/java/ru/yandex/practicum/validator/FilmValidatorTest.java
> +public class FilmValidatorTest {
убрал в 1 пул контроллера, подумал что тесты задевают логику только контроллера

2022-12-09 20:13 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/controller/FilmController.java
> +@JsonAutoDetect(getterVisibility = JsonAutoDetect.Visibility.NONE)
Не исправлено

2022-12-09 20:14 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/controller/FilmController.java
> +    public Integer getId(){
Не исправлено

2022-12-09 20:14 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/controller/UserController.java
> +    public Integer getId(){
Не исправлено

2022-12-09 20:19 UTC, Anthony-Elvek commented on src/main/java/ru/yandex/practicum/controller/FilmController.java
> +@JsonAutoDetect(getterVisibility = JsonAutoDetect.Visibility.NONE)
извините, я сначала все переделал под сервис но не мог долго понять что не так, и вернул все обратно и забыл исправить, сейчас добавлю

2022-12-09 20:21 UTC, NikolaiDem requested changes

2022-12-09 20:21 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/validator/ReleaseDateValidator.java
> +    @Override
Кодстайл - расстояние между методами полями должно составлять одну пустую строку.

2022-12-10 09:53 UTC, NikolaiDem approved these changes

2022-12-10 13:22 UTC, merged