first try
Anthony-Elvek/java-filmorate pull request #3
Opened 2022-12-25 19:46 UTC by Anthony-Elvek

2022-12-25 19:47 UTC, Anthony-Elvek commented
Здравствуйте, можете помочь: не могу понять почему многие тесты падают, не могу сдвинутся с мертвой точки

2022-12-26 00:58 UTC, NikolaiDem requested changes

2022-12-26 00:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/controller/ErrorHandler.java
> +        return ResponseEntity
Лучше залогировать причину исключения.
Аналогично для остальных методов.

2022-12-26 00:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/storage/userStorage/InMemoryUserStorage.java
> +        return users.get(userId);
Если пользователь не найден, лучше бросить исключение NotFoundException.

2022-12-26 00:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/storage/userStorage/InMemoryUserStorage.java
> +        if(!users.get(userId).getFriends().contains(friendId)){
Почему "!" ?

2022-12-26 00:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/storage/filmStorage/InMemoryFilmStorage.java
> +        if (films.containsKey(film.getId())) {
Если фильма не существует в коллекции, то лучше бросить NotFoundException.

2022-12-26 00:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/storage/filmStorage/InMemoryFilmStorage.java
> +        return films.get(filmId);
Если фильма не существует в коллекции, то лучше бросить NotFoundException.

2022-12-26 00:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/storage/filmStorage/InMemoryFilmStorage.java
> +    public void addLike(Long filmId, Long userId) {
Хранилище занимается лишь сохранением/получением данных. Методы с логикой (добавление, удаление лайка и  определение популярных фильмов) лучше оставить в сервисе. Перенести логику туда.

2022-12-26 00:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/storage/userStorage/InMemoryUserStorage.java
> +        if (users.containsKey(user.getId())) {
Если юзера не существует в коллекции, то лучше бросить NotFoundException.

2022-12-26 00:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/storage/userStorage/InMemoryUserStorage.java
> +    public void addFriend(Long userId, Long friendId) {
Логику по добавлению, удалению из друзей, поиск общих друзей и друзей пользователя лучше перенести в сервис.

2022-12-26 00:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/storage/userStorage/InMemoryUserStorage.java
> +                .filter(id -> users.get(friendId).getFriends().contains(id))
users.get(friendId).getFriends() вынести в отдельную переменную.

2022-12-26 00:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/controller/ErrorHandler.java
> +    @ExceptionHandler(Throwable.class)
Добавить еще одно исключение:
    @ExceptionHandler({ValidationException.class, MethodArgumentNotValidException.class})

2022-12-26 00:58 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/controller/FilmControllerTest.java
Починить тесты.

2022-12-26 00:58 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/controller/UserControllerTest.java
Починить тесты.

2022-12-26 00:58 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/controller/UserControllerTest.java
> +    private UserService userService;
Так как сейчас появились сервисы, то нужно описать их поведение в тесте. Иначе сейчас мок бина существует, но возвращает он просто null, поэтому тесты и падают.
Поэтому, там где нужно описать поведение замоканного сервиса, можно использовать, например,
Mockito.when(userService.update(Mockito.any())).thenReturn(user);

2022-12-26 20:59 UTC, Anthony-Elvek commented
Здравствуйте, исправил замечания как понял, но почему то логика все равно плохо отрабатывается, может я еще где то ошибку сделал?

2022-12-27 22:36 UTC, NikolaiDem requested changes

2022-12-27 22:36 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/model/Film.java
> +    private final Set<Long> likes;
Нужно инициализировать коллекцию, иначе будет NPE.

2022-12-27 22:36 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/model/User.java
> +    private final Set<Long> friends;
Нужно инициализировать коллекцию, иначе будет NPE.

2022-12-27 22:36 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/model/ErrorResponse.java
> +    private final String error;
Добавить геттер.

2022-12-28 15:28 UTC, NikolaiDem approved these changes

2023-01-08 19:00 UTC, merged