Add database
Anthony-Elvek/java-filmorate pull request #4
Opened 2023-02-10 07:54 UTC by Anthony-Elvek

Здравствуйте, Можете пожалуйста указать на ошибки, уж больно долго мучаюсь с ошибками, заранее большое спасибо!

2023-02-11 01:56 UTC, NikolaiDem requested changes
Нужно починить сборку)

2023-02-13 13:39 UTC, Anthony-Elvek commented
Поправил полностью сборку, только 1 тест не проходит, его не было в ТЗ и я ни как не могу понять, можете подсказать, почему когда приходит такой запрос "film/popular" без параметров у меня 500??

2023-02-13 15:18 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/dao/genreStorage/GenreDbStorage.java
> +
лишняя пустая строка после аннотаций

2023-02-13 15:18 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/service/FilmService.java
> +        return filmStorage.findMostPopularFilms(count);
Я тебе предлагаю написать простейший юнит тест на этот метод и ты сразу увидишь в чем ошибка, из за него валятся постман тесты, сразу будет видно при дебаге в чем ошибка ;-)

2023-02-13 16:15 UTC, Anthony-Elvek commented on src/main/java/ru/yandex/practicum/service/FilmService.java
> +        return filmStorage.findMostPopularFilms(count);
я честно не могу понять, если бы была проблема с тестом тогда бы параметризированные тесты бы так же упали с 500 ошибкой, здесь разве не нужно писать отдельный метод?

2023-02-15 10:05 UTC, merged